image: php:7.2
clone:
  depth: 1

pipelines:
  default:
    - step:
        name: PHP oriented tasks
        caches:
          - composer
        script:
          # Update Composer, install dependencies
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer self-update
          - composer install --prefer-dist --no-interaction

          # Create results directory
          - mkdir ./test-reports

          # Run phpstan
          - composer --no-ansi run-phpstan

          # Run unit tests
          - composer --no-ansi run-tests -- --log-junit ./test-reports/phpunit.xml
